//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteSFATestWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-test2.arabesque.ro:8000/sap/bc/srt/rfc/sap/ztest_itab/900/ztest_itab/z" +
            "test_itab")]
        public string LiteSFATestWebService_WEBTable_ZTEST_ITABService {
            get {
                return ((string)(this["LiteSFATestWebService_WEBTable_ZTEST_ITABService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zwbs_znecesar1/900/zwbs_zne" +
            "cesar1/zwbs_znecesar1")]
        public string LiteSFATestWebService_WebNecesar1_ZWBS_ZNECESAR1Service {
            get {
                return ((string)(this["LiteSFATestWebService_WebNecesar1_ZWBS_ZNECESAR1Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-test1a.arabesque.ro:8081/sap/bc/srt/rfc/sap/ztbl_webservice/900/ztbl_w" +
            "ebservice/ztbl_webservice")]
        public string LiteSFATestWebService_SapWebServices_ZTBL_WEBSERVICE {
            get {
                return ((string)(this["LiteSFATestWebService_SapWebServices_ZTBL_WEBSERVICE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-test1a.arabesque.ro:8081/sap/bc/srt/rfc/sap/zclp_webservice/900/zclp_w" +
            "ebservice/zclp_webservice")]
        public string LiteSFATestWebService_SAPWebServiceCLP_ZCLP_WEBSERVICEService {
            get {
                return ((string)(this["LiteSFATestWebService_SAPWebServiceCLP_ZCLP_WEBSERVICEService"]));
            }
        }
    }
}
