//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zclp_webservice/900/zclp_we" +
            "bservice/zclp_webservice")]
        public string WebService1_SapWsClp_ZCLP_WEBSERVICE {
            get {
                return ((string)(this["WebService1_SapWsClp_ZCLP_WEBSERVICE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zwbs_zintrarimarfa/900/zwbs" +
            "_zintrarimarfa/zwbs_zintrarimarfa")]
        public string WebService1_WebNecesar1_ZWBS_ZINTRARIMARFA {
            get {
                return ((string)(this["WebService1_WebNecesar1_ZWBS_ZINTRARIMARFA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.bizpack.ro/wsi/service.php")]
        public string WebService1_SMSService_SMSServiceService {
            get {
                return ((string)(this["WebService1_SMSService_SMSServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zwbs_semiactivi/900/zwbs_se" +
            "miactivi/zwbs_semiactivi")]
        public string WebService1_ClientiSemiactivi_ZWBS_SEMIACTIVI {
            get {
                return ((string)(this["WebService1_ClientiSemiactivi_ZWBS_SEMIACTIVI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zwbs_sal_av/900/zwbs_sal_av" +
            "/zwbs_sal_av")]
        public string WebService1_WebServiceSalarizareAV_ZWBS_SAL_AV {
            get {
                return ((string)(this["WebService1_WebServiceSalarizareAV_ZWBS_SAL_AV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zfg_instr_plata/900/zfg_ins" +
            "tr_plata/zfg_instr_plata")]
        public string WebService1_PlataNeincasate_ZFG_INSTR_PLATA {
            get {
                return ((string)(this["WebService1_PlataNeincasate_ZFG_INSTR_PLATA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zws_custodie/900/zwbs_custo" +
            "die/zwbs_custodie")]
        public string WebService1_SAPWSCustodie1_ZWBS_CUSTODIE {
            get {
                return ((string)(this["WebService1_SAPWSCustodie1_ZWBS_CUSTODIE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zws_salarizare_2019/900/zws" +
            "_salarizare_2019/zws_salarizare_2019")]
        public string WebService1_Salarizare2019_ZWS_SALARIZARE_2019 {
            get {
                return ((string)(this["WebService1_Salarizare2019_ZWS_SALARIZARE_2019"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zws_sal_ka_2019/900/zws_sal" +
            "_ka_2019/zws_sal_ka_2019")]
        public string WebService1_SalarizareKA_ZWS_SAL_KA_2019 {
            get {
                return ((string)(this["WebService1_SalarizareKA_ZWS_SAL_KA_2019"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zws_cl_fact_avsd/900/zws_cl" +
            "_fact_avsd/zws_cl_fact_avsd")]
        public string WebService1_SapWSPierderiVanzari_ZWS_CL_FACT_AVSD {
            get {
                return ((string)(this["WebService1_SapWSPierderiVanzari_ZWS_CL_FACT_AVSD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zwms_ul10_get_stock_arab/90" +
            "0/zwms_ul10_get_stock_arab/zwms_ul10_get_stock_arab")]
        public string WebService1_SapWsCabluri05_ZWMS_UL10_GET_STOCK_ARAB {
            get {
                return ((string)(this["WebService1_SapWsCabluri05_ZWMS_UL10_GET_STOCK_ARAB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zws_sal_cva/900/zws_sal_cva" +
            "/zws_sal_cva")]
        public string WebService1_SalarizareCVA_ZWS_SAL_CVA {
            get {
                return ((string)(this["WebService1_SalarizareCVA_ZWS_SAL_CVA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/zws_salarizare_24/900/zws_s" +
            "alarizare_24/zws_salarizare_24")]
        public string WebService1_SapWsSalarizare_ZWS_SALARIZARE_24 {
            get {
                return ((string)(this["WebService1_SapWsSalarizare_ZWS_SALARIZARE_24"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sap-prd4a.arabesque.ro:8034/sap/bc/srt/rfc/sap/ztbl_webservice/900/ztbl_we" +
            "bservice/ztbl_webservice")]
        public string WebService1_SAPWebServices_ZTBL_WEBSERVICEService {
            get {
                return ((string)(this["WebService1_SAPWebServices_ZTBL_WEBSERVICEService"]));
            }
        }
    }
}
